# Generated by Django 4.2.4 on 2023-10-16 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_thoughts', '0008_alter_thought_shared_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='shared_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='thoughts', to=settings.AUTH_USER_MODEL),
        ),
    ]
